version: '3.8'
services:
  web-app:
    container_name: tecsus-frontend-container-prod
    image: tecsus-frontend-image-prod
    build:
      context: .
      dockerfile: Dockerfile.prod   
    ports:
      - "80:80"
    volumes:
      - .:/app  
    environment: 
      - CHOKIDAR_USEPOLLING=true