version: "3"
services:
  frontend:
    container_name: tecsus-frontend-container
    build: 
      context: .
    volumes:
      - .:/app
    ports: 
      - 8080:8080
    environment: 
      - CHOKIDAR_USEPOLLING=true