version: "3"
services:
  frontend:
    container_name: tecsus-frontend-container
    image: tecsus-frontend-image
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports: 
      - 80:80
    environment: 
      - CHOKIDAR_USEPOLLING=true