# Use a imagem do backend do Docker Hub como base
FROM datateam23/tecsus-backend:latest

WORKDIR /app

# Garante que o usuário nonroot é usado
USER nonroot

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]