# Use a imagem do backend do Docker Hub como base
FROM datateam23/tecsus-backend:latest

# Adicionar um novo usuário não privilegiado
RUN addgroup nonroot
RUN adduser nonroot nonroot
USER nonroot

WORKDIR /app

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]