name: Build and Unit Tests Pipeline

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "dev"
      - "main"

jobs:
  setup: 
    name: Setup Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18


  verify-dependencies:
    name: Verify Dependencies
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
        working-directory: app-web
    
  
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    needs:
      - setup
      - verify-dependencies
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
      
      - name: Run Build project
        run: npm run build
        working-directory: app-web


  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs:
      - setup
      - verify-dependencies
      - build-project
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Run tests
        run: npm run test
        working-directory: app-web

