name: Unit Tests

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "dev"
      - "main"

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup Config
        uses: .github/workflows/setup.yml

      - name: Run tests
        run: npm run test
        working-directory: app-web