name: Verify Dependencies

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "dev"
      - "main"

jobs:
  verify-dependencies:
    name: Setup Config
    runs-on: ubuntu-latest

    steps:
      - name: Setup Config
        uses: .github/workflows/setup.yml

      - name: Install dependencies
        run: npm install
        working-directory: app-web
